// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz2_aeo0w7T2VyC2pK45_6ytd2hiAY-zU',
    appId: '1:404169488931:web:7140a90b282e5e2d9e8f96',
    messagingSenderId: '404169488931',
    projectId: 'voyake-42b11',
    authDomain: 'voyake-42b11.firebaseapp.com',
    storageBucket: 'voyake-42b11.appspot.com',
    measurementId: 'G-RLVZ70BSD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF53s4d6-cAfZZZI9_c_A3OYHs5DqIFZQ',
    appId: '1:404169488931:android:4304637fcde87b0a9e8f96',
    messagingSenderId: '404169488931',
    projectId: 'voyake-42b11',
    storageBucket: 'voyake-42b11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG9f-4GSDyR-BIHFZT-9TDXLFxYi7Z1Bg',
    appId: '1:404169488931:ios:54d22280f13543bf9e8f96',
    messagingSenderId: '404169488931',
    projectId: 'voyake-42b11',
    storageBucket: 'voyake-42b11.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG9f-4GSDyR-BIHFZT-9TDXLFxYi7Z1Bg',
    appId: '1:404169488931:ios:67e929c080c250289e8f96',
    messagingSenderId: '404169488931',
    projectId: 'voyake-42b11',
    storageBucket: 'voyake-42b11.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
